== *Practice 6*: Reflection

Slides 28-31

If a module want to access to other module's components, other module have to open or export required packages to caller module.

exports:: Makes packages accessible to other modules at compile time or run time.

opens:: Makes packages accessible to other modules only at run time including access to private members.

[NOTE]
====
[source,java]
----
Class<?> clazz = Class.forName("com.printer.impl.Printer"); <1>
Class<Printer> clazz = Printer.class; <2>
----
<1> Access to the class at run-time
<2> Access to the class at compile time

====

Reflective access with exports (private method)

In this practice, you are going to play with ``exports``, ``requires`` and ``opens`` keywords to understand them easily.

[source,bash]
----
cd module-reflection-exports-private
----

Compile ``printer-impl`` and ``printer-client`` modules, and log that how Java module system prevents access when `opens` is missed.

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make private void com.printer.impl.Printer.print(java.lang.String) accessible: module com.printer.
impl does not "opens com.printer.impl" to module com.printer.client
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
        at com.printer.client/com.printer.client.PrinterClient.main(PrinterClient.java:10)

////

Update `printer-impl/src/module-info.java` and `printer-client/src/module-info.java` for the reflection operation on private data to work.

////
Hello world
////
